# Generated by Django 4.2 on 2023-04-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattclimbapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exposure',
        ),
        migrations.RemoveField(
            model_name='climb',
            name='style',
        ),
        migrations.AddField(
            model_name='climb',
            name='hold_type',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='climbs_holds', to='chattclimbapi.holdtype'),
        ),
        migrations.AddField(
            model_name='climb',
            name='steep',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='climbs_steep', to='chattclimbapi.steep'),
        ),
        migrations.AlterField(
            model_name='holdtype',
            name='type',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
