# Generated by Django 4.2 on 2023-04-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattclimbapi', '0002_delete_exposure_remove_climb_style_climb_hold_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='crag',
            name='access',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='crag',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='crag',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='crag_state', to='chattclimbapi.state'),
        ),
    ]
